In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
raw_data = pd.read_csv('countries.csv')


In [3]:
raw_data.head()

countries  year  population
0  New Zealand  1952     1994794
1  New Zealand  1957     2229407
2  New Zealand  1962     2488550
3  New Zealand  1967     2728150
4  New Zealand  1972     2929100

In [4]:
raw_data.isnull().sum()

countries     0
year          0
population    0
dtype: int64

In [5]:
Niger = raw_data[raw_data.countries == 'Niger']
New_Zea = raw_data[raw_data.countries == 'New Zealand']
Nicar = raw_data[raw_data.countries == 'Nicaragua']
Nigeria = raw_data[raw_data.countries == 'Nigeria']
Norw = raw_data[raw_data.countries == 'Norway']

Niger.to_csv('Niger.csv', index=False)
New_Zea.to_csv('NewZealand.csv', index=False)
Nicar.to_csv('Nicaragua.csv', index=False)
Nigeria.to_csv('Nigeria.csv', index=False)
Norw.to_csv('Norway.csv', index=False)

In [6]:
#model building for each of the country
#for Niger

In [7]:
niger_data=pd.read_csv('Niger.csv')
niger_data.head()

countries  year  population
0     Niger  1952     3379468
1     Niger  1957     3692184
2     Niger  1962     4076008
3     Niger  1967     4534062
4     Niger  1972     5060262

In [8]:
from sklearn.model_selection import cross_validate
from sklearn import preprocessing, tree

X=niger_data.drop(['population', 'countries'], axis=1)
y=niger_data['population']

print(len(X), len(y))

12 12


In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn import ensemble
rlf = ensemble.RandomForestRegressor(n_estimators=50)
rlf.fit(X_train, y_train)
Accuracy = rlf.score(X_test, y_test)

print(Accuracy)

0.9135398413478257


In [18]:
#saving models
import joblib

#saving the model as a pickle file
joblib.dump(rlf, 'Niger.pkl')

#loading the model from the file
rlf_from_joblib = joblib.load('Niger.pkl')

#using the model to make predictions

rlf_from_joblib.predict(X_test)





array([10598338.2 ,  8595936.48,  3848307.64,  7259094.96])

In [20]:
#model building for New Zealand
New_Zea_data = pd.read_csv('NewZealand.csv')
New_Zea_data.head()

countries  year  population
0  New Zealand  1952     1994794
1  New Zealand  1957     2229407
2  New Zealand  1962     2488550
3  New Zealand  1967     2728150
4  New Zealand  1972     2929100

In [21]:
New_Zea_data.drop(['countries'], axis=1, inplace=True)

In [22]:
X=New_Zea_data.drop(['population'], axis=1)
y=New_Zea_data['population']

print(len(X), len(y))

12 12


In [24]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.3, random_state=42)
Rfr = ensemble.RandomForestRegressor(n_estimators=50)
Rfr.fit(X_train, y_train)
accuracy = Rfr.score(X_test, y_test)

print(accuracy)

0.922368606729376


In [25]:
#saving model as a pickle file
joblib.dump(Rfr, 'New Zealand.pkl')

#loading the model from the file
rlf_from_joblib = joblib.load('New Zealand.pkl')

#using the model to make predictions

rlf_from_joblib.predict(X_test)



array([3837854.34, 3486468.14, 2331500.76, 3301783.94])

In [27]:
#model building for Nicaragua
Nicar_data = pd.read_csv('Nicaragua.csv')
Nicar_data.head()

countries  year  population
0  Nicaragua  1952     1165790
1  Nicaragua  1957     1358828
2  Nicaragua  1962     1590597
3  Nicaragua  1967     1865490
4  Nicaragua  1972     2182908

In [28]:
Nicar_data.drop(['countries'], axis=1, inplace=True)

In [29]:
X=Nicar_data.drop(['population'], axis=1)
y=Nicar_data['population']
print(len(X), len(y))

12 12


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)
RFG=ensemble.RandomForestRegressor(n_estimators=50)
RFG.fit(X_train, y_train)
AccuracY=RFG.score(X_test,y_test)
print(AccuracY)

0.8154418204396185


In [32]:
#saving model as a pickle file
joblib.dump(RFG, 'Nicaragua.pkl')

#loading the model from the file
rlf_from_joblib = joblib.load('Nicaragua.pkl')

#using the model to make predictions

rlf_from_joblib.predict(X_test)



array([4790304.98, 3671423.54, 1486751.28, 3223081.26])

In [33]:
#model building for Nigeria
Nigeria_data=pd.read_csv('Nigeria.csv')
Nigeria_data.head()

countries  year  population
0   Nigeria  1952    33119096
1   Nigeria  1957    37173340
2   Nigeria  1962    41871351
3   Nigeria  1967    47287752
4   Nigeria  1972    53740085

In [35]:
Nigeria_data.drop(['countries'], axis=1, inplace=True)


In [36]:
X=Nigeria_data.drop(['population'], axis=1)
y=Nigeria_data['population']

print(len(X), len(y))

12 12


In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)
rfg=ensemble.RandomForestRegressor(n_estimators=50)
rfg.fit(X_train, y_train)
ACCuracy=rfg.score(X_test,y_test)
print(ACCuracy)

0.9078257680878746


In [38]:
#saving the model as a pickle file
joblib.dump(rfg, 'Nigeria.pkl')
#loading the model
rfg_from_joblib=joblib.load('Nigeria.pkl')
#making predictions
rfg_from_joblib.predict(X_test)

array([1.17020102e+08, 9.45586519e+07, 3.96436387e+07, 7.85976024e+07])

In [39]:
#model building for Norway
Norway_data=pd.read_csv('Norway.csv')
Norway_data.head()

countries  year  population
0    Norway  1952     3327728
1    Norway  1957     3491938
2    Norway  1962     3638919
3    Norway  1967     3786019
4    Norway  1972     3933004

In [40]:
Norway_data.drop(['countries'], axis=1, inplace=True)

In [41]:
X=Norway_data.drop('population', axis=1)
y=Norway_data['population']
print(len(X), len(y))

12 12


In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)
RFg=ensemble.RandomForestRegressor(n_estimators=50)
RFg.fit(X_train,y_train)
ACCUracy=RFg.score(X_test,y_test)
print(ACCUracy)

0.8901007785128338


In [43]:
#saving the model as a pickle file
joblib.dump(RFg, 'Norway.pkl')
#loading the data
RFg_from_joblib=joblib.load('Norway.pkl')
#making predictions
RFg_from_joblib.predict(X_test)

array([4460322.36, 4230597.28, 3550739.92, 4169020.6 ])